import SwiftUI

/// 具体物カードの絵柄（#1243・#1244）。カードしりとりと神経衰弱が同じ絵を使う。
///
/// **OS の絵文字は使わない**（意匠が iOS のバージョンで変わるため）。チャリンコおじさんと同じ
/// ドット絵（`PixelSprite`）で、**40×40 ドット・外側に 1 ドットの縁取り**に揃えてある
/// （#1287 で 20×20 から 2 倍に上げた。会長指摘「全体的に粗い」）。
/// 描き方: 図形（楕円・矩形・多角形・線）を部品ごとに重ね、部品単位で縁取りを自動で付けてから
/// 文字列にした（部品の境目に 1 ドットの線が入る）。影は三日月形に 1 段暗い色を落とし、
/// 目には 1 ドットの光を入れる。
///
/// `rawValue` は**中断データに書く識別子**になりうるので、一度出した値は変えない。
public enum ObjectCardKind: String, CaseIterable, Sendable, Codable {
    case apple, gorilla, seaOtter, koala, camel, rabbit, guitar, drum, kitten, glass
    case squirrel, watermelon, turtle, eyeglasses, cat, spinningTop, pillow, ostrich, handFan, crocodile
    /// #1245 で 20 → 30 枚に増やした 10 種。連鎖が伸びやすいよう語頭・語尾を重ねて選んだ。
    case boat, leek, ball, mushroom, horse, deer, cow, bell, moon, octopus

    /// VoiceOver の読み上げ文。絵だけのカードなので、言葉はここで持つ。
    public var displayName: String {
        switch self {
        case .apple:       return "りんご"
        case .gorilla:     return "ゴリラ"
        case .seaOtter:    return "ラッコ"
        case .koala:       return "コアラ"
        case .camel:       return "ラクダ"
        case .rabbit:      return "ウサギ"
        case .guitar:      return "ギター"
        case .drum:        return "たいこ"
        case .kitten:      return "こねこ"
        case .glass:       return "コップ"
        case .squirrel:    return "リス"
        case .watermelon:  return "スイカ"
        case .turtle:      return "カメ"
        case .eyeglasses:  return "めがね"
        case .cat:         return "ネコ"
        case .spinningTop: return "こま"
        case .pillow:      return "まくら"
        case .ostrich:     return "ダチョウ"
        case .handFan:     return "うちわ"
        case .crocodile:   return "ワニ"
        case .boat:        return "ふね"
        case .leek:        return "ねぎ"
        case .ball:        return "まり"
        case .mushroom:    return "きのこ"
        case .horse:       return "うま"
        case .deer:        return "しか"
        case .cow:         return "うし"
        case .bell:        return "すず"
        case .moon:        return "つき"
        case .octopus:     return "たこ"
        }
    }

    /// ドット絵の 1 辺（ドット）。全種そろっている（テストが縛る）。
    public static let dots = 40

    public var sprite: PixelSprite {
        switch self {
        case .apple:       return ObjectCardSprites.apple
        case .gorilla:     return ObjectCardSprites.gorilla
        case .seaOtter:    return ObjectCardSprites.seaOtter
        case .koala:       return ObjectCardSprites.koala
        case .camel:       return ObjectCardSprites.camel
        case .rabbit:      return ObjectCardSprites.rabbit
        case .guitar:      return ObjectCardSprites.guitar
        case .drum:        return ObjectCardSprites.drum
        case .kitten:      return ObjectCardSprites.kitten
        case .glass:       return ObjectCardSprites.glass
        case .squirrel:    return ObjectCardSprites.squirrel
        case .watermelon:  return ObjectCardSprites.watermelon
        case .turtle:      return ObjectCardSprites.turtle
        case .eyeglasses:  return ObjectCardSprites.eyeglasses
        case .cat:         return ObjectCardSprites.cat
        case .spinningTop: return ObjectCardSprites.spinningTop
        case .pillow:      return ObjectCardSprites.pillow
        case .ostrich:     return ObjectCardSprites.ostrich
        case .handFan:     return ObjectCardSprites.handFan
        case .crocodile:   return ObjectCardSprites.crocodile
        case .boat:        return ObjectCardSprites.boat
        case .leek:        return ObjectCardSprites.leek
        case .ball:        return ObjectCardSprites.ball
        case .mushroom:    return ObjectCardSprites.mushroom
        case .horse:       return ObjectCardSprites.horse
        case .deer:        return ObjectCardSprites.deer
        case .cow:         return ObjectCardSprites.cow
        case .bell:        return ObjectCardSprites.bell
        case .moon:        return ObjectCardSprites.moon
        case .octopus:     return ObjectCardSprites.octopus
        }
    }

    /// 1 ドット = 2px（80×80）で持つビットマップ。起動後 1 回だけ作る（毎表示でビットマップ化しない）。
    /// 20×20 のときは 4px で持っていた。画素数（80×80・30 枚で約 0.8MB）と初回生成の時間を据え置くために
    /// 倍率を半分にしている。描画は `.interpolation(.none)` で枠に合わせて伸縮するので見た目は変わらない。
    private static let images: [ObjectCardKind: CGImage] = {
        var out: [ObjectCardKind: CGImage] = [:]
        for kind in allCases { if let cg = kind.sprite.cgImage(scale: 2) { out[kind] = cg } }
        return out
    }()

    public var cgImage: CGImage? { Self.images[self] }
}

/// 具体物カードの絵。枠いっぱいに整数倍でなくても、補間せずドットの縁を立てる。
/// 装飾扱い（VoiceOver は親のカードが `displayName` で読む）。
public struct ObjectCardArt: View {
    private let kind: ObjectCardKind

    public init(_ kind: ObjectCardKind) { self.kind = kind }

    public var body: some View {
        if let cg = kind.cgImage {
            Image(decorative: cg, scale: 1).renderingMode(.original).resizable().interpolation(.none)
                .aspectRatio(1, contentMode: .fit)
        } else {
            Image(systemName: "questionmark.square").resizable().aspectRatio(1, contentMode: .fit)
        }
    }
}

// MARK: - ドット絵

enum ObjectCardSprites {
    static let apple = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            ".....................K........KKKK......",
            "....................KaK....KKKbbbbK.....",
            "...................KaaaK.KKbbbbbbbbK....",
            "...................KaaK.KbbbbbbbccbK....",
            "...................KaaKKbbbbbbccbbbK....",
            "............K.....KaaaKbbbbcccbbbbK.....",
            "........KKKKdKKK..KaaKbbbccbbbbbbK......",
            ".......KddddddddK.KaaKbccbbbbbbbK.......",
            "......KdddddddddKKaaaKbbbbbbbbKKK.......",
            ".....KddddddddddddKaKdKbbbbKKKdddK......",
            "....KddddddddddddddKdddKKKKdddddddK.....",
            "...KdddddddddddddddddddddddddddddddK....",
            "...KdddddddddddddddddddddddddddddddK....",
            "...KdddddeeedddddddddddddddddddddddK....",
            "...KdddddeeeeddddddddddddddddddddddK....",
            "...KdddddeeeeddddddddddddddddddfdddK....",
            "....KddddeeeeeddddddddddddddddddfdK.....",
            "....KddddeeeeeddddddddddddddddddffK.....",
            "....KddddeeeeeddddddddddddddddddffK.....",
            "....KddddeeeeedddddddddddddddddddfK.....",
            "....KdddddeeeedddddddddddddddddddfK.....",
            "....KdddddeeeedddddddddddddddddddfK.....",
            "....KddddddeeedddddddddddddddddddfK.....",
            "....KddddedddddddddddddddddddddddfK.....",
            "....KdddeeeddddddddddddddddddddddfK.....",
            "....KdddeeedddddddddddddddddddddffK.....",
            "....KddddeddddddddddddddddddddddffK.....",
            ".....KddddddddddddddddddddddddddfK......",
            "......KddddddddddddddddddddddddfK.......",
            "......KdddddddddddddddddddddddffK.......",
            ".......KdddddddddddddddddddddffK........",
            "........KdddddddddddddddddddffK.........",
            ".........KKdddddddfddddddfffKK..........",
            "...........KKddddddfffffffKK............",
            ".............KKdddddffffKK..............",
            "...............KKKKKKKKK................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x6B4423, "b": 0x39A85B, "c": 0x2C7F44, "d": 0xE24A3C, "e": 0xFF9C8C, "f": 0xB8322A]
    )

    static let gorilla = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "................KKKKKKK.................",
            ".............KKKaaaaaaaKKK..............",
            "............KaaaaaaaaaaaaaK.............",
            "...........KbaaaaaaaaaaaaabK............",
            "..........KbbbaaaaaaaaaaabbbK...........",
            ".........KbbbbcccccccccccbbbbK..........",
            "........KbbbcccccccccccccccbbbK.........",
            "........KbbcccccccccccccccccbbK.........",
            ".......KbbbbcccccccccccccccbbbbK........",
            ".......KbbbbbdeeeccccceeedbbbbbK........",
            ".......KbbbbdeeeeedddeeeeedbbbbK........",
            ".......KbbbbdeeffedddeeffedbbbbK........",
            ".......KbbbddeeffedddeeffeddbbbK........",
            ".......KbbbdddeeedddddeeedddbbbK........",
            ".......KbbbdddddddcccdddddddbbbK........",
            ".......KbbbdddddcccccccdddddbbbK........",
            "........KbbdddddccfccfcdddddbbK.........",
            "........KbbdddddcccccccdddddbbK.........",
            ".........KbbddddddcccddddddbbK..........",
            "..........KbdddddddddddddddbK...........",
            "...........KbddcccccccccddbK............",
            "............KbbdddddddddbbK.............",
            "........KKKKKKKKbbbdbbbKKKKKKKK.........",
            ".....KKKbbbbbbbbKKKKKKKbbbbbbbbKKK......",
            "....KaaabbbbbbbbbbbbbbbbbbbbbbbaaaK.....",
            "...KaaaaabbbbbbbbbbbbbbbbbbbbbaaaaaK....",
            "..KaaaaaabbbbbbaaaaaaaaabbbbbbaaaaaaK...",
            ".KbaaaaaabbbaaaaaaaaaaaaaaabbbaaaaaabK..",
            ".KaaaaaaaabaaaaaaaaaaaaaaaaabaaaaaaaaK..",
            "..KaaaaaaabaaaaaaaaaaaaaaaaabaaaaaaaK...",
            "...KaaaaabbaaaaaaaaaaaaaaaaabbaaaaaK....",
            "....KaaaabbaaaaaaaaaaaaaaaaabbaaaaK.....",
            ".....KKKabbbaaaaaaaaaaaaaaabbbaKKK......",
            "........KKKKKbbaaaaaaaaabbKKKKK.........",
            ".............KKKKKKKKKKKKK..............",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x3E4049, "b": 0x5A5F6B, "c": 0x5E534E, "d": 0x8C7F78, "e": 0xFFFFFF, "f": 0x2B2B33]
    )

    static let seaOtter = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "................KKKKKKK.................",
            ".......KKKK...KKaaaaaaaKK...KKKK........",
            "......KaaaaKKKaaaaaaaaaaaKKKaaaaK.......",
            "......KabbaKaaaaaaaaaaaaaaaKabbaK.......",
            "......KabbaKaaaaaaaaaaaaaaaKabbaK.......",
            ".......KKKKacddaKKKKKKKacddaKKKK........",
            "........KaaadddKeeeeeeeKdddaaaK.........",
            ".......KaaaadddeeeeeeeeedddaaaaK........",
            ".......KaaaaKeeeeebbbeeeeeKaaaaK........",
            "......KaaaaaKeeeebbbbbeeeeKaabaaK.......",
            "......KaaaaaKeeeeebbbeeeeeKaaabaK.......",
            "......KaaaaaKeeeeeebeeeeeeKaaaabK.......",
            ".....KaaaaaaKeeeeeebeeeeeeKaaaabbK......",
            ".....KaaaaaaKeeeebbbbbeeeeKaaaabbK......",
            ".....KaaaaaaaKKeebbbbbeeKKaaaaaabK......",
            ".....KaaaaaaaaaKeKKKKKeKaaaaaaaabK......",
            ".....KaaaaaKKKKKKffgffKKKKKKaaaabK......",
            ".....KaaaaKaaaaKffgggffKaaaaKaaabK......",
            ".....KaaaKaaaaaaKgfgfgKaaaaaaKaabK......",
            ".....KaaaKaaaaaaKgfgfgKaaaaaaKaabK......",
            "......KaaaKaaaaKgffgffgKaaaaKaabK.......",
            "......KaaaaKKKKgfffgfffgKKKKaaabK.......",
            "......KaaaeeeeeKKffgffKKeeeeeaabK.......",
            ".......KaeeeeeeeeKKKKKeeeeeeeebK........",
            ".......KaeeeeeeeeeeeeeeeeeeeeebK........",
            "........KeeeeeeeeeeeeeeeeeeeeeK.........",
            ".........KeeeeeeeeeeeeeeeeeeeK..........",
            ".KKKKKKKKKKeeeeeeeeeeeeeeeeeKKKKKKKKKKK.",
            "KhhhcchhhhhKeeeeeeeeeeeeeeeKcchhhhcchhhK",
            "KhhhhhhhhhhhKKaeeeeeeeeebKKhhhhhhhhhhhhK",
            "KhhhhhhhhhhhhhKKaabbbbbKKhhhhhhhhhhhhhhK",
            "KhhhhhhhhhhhhhhhKKKKKKKhhhhhhhhhhhhhhhhK",
            ".KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x9A6A3A, "b": 0x6B4423, "c": 0xFFFFFF, "d": 0x2B2B33, "e": 0xF7E8C8, "f": 0xF4A6B7, "g": 0xE06C8B, "h": 0xBFE3F5]
    )

    static let koala = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "......KKKK....................KKKK......",
            "....KKaaaaKK................KKaaaaKK....",
            "...KaaaaaaaaK..............KaaaaaaaaK...",
            "..KaaaaaaaaaaK..KKKKKKK...KaaaaaaaaaaK..",
            ".KaaaaabbaaaaKKKaaaaaaaKKKaaaaabbaaaaaK.",
            ".KaaabbbbbbaKaaaaaaaaaaaaaKaabbbbbbaaaK.",
            ".KaaabbbbbKKaaaaaaaaaaaaaaaKKbbbbbbaaaK.",
            "KaaabbbbbKaaaaaaaaaaaaaaaaaaaKbbbbbbaaaK",
            ".KaabbbbKaaaaaaaaaaaaaaaaaaaaaKbbbbbaaK.",
            ".KaaabbbKaaaaaaaaaaaaaaaaaaaaaKbbbbaaaK.",
            ".KaaabbKaaaacccaaaaaaaaacccaaaaKbbbaaaK.",
            "..KaaaKaaaaadccaaaaaaaaadccaaaaeKaaaaK..",
            "...KaaKaaaaacccaaaaaaaaacccaaaaaKaaaK...",
            "....KKKaaaaacccaaacccaaacccaaaaaKaKK....",
            "......KaaaaaaaaaaffcccaaaaaaaaaaKK......",
            "......KaaaaaaaaacfffcccaaaaaaaaaK.......",
            "......KaaaaaaaaacffccccaaaaaaaaaK.......",
            "......KaaaaaaaaacccccccaaaaaaaaaK.......",
            "......KaagggggaacccccccaagggggaaK.......",
            "......KagggggggacccccccagggggggaK.......",
            "......KgggggggggcccccccgggggggggK.......",
            ".......KggggggggacccccaggggggggK........",
            "........KggggggaaacccaaaggggggK.........",
            "........KgggggaaaaaaaaaaagggggK.........",
            ".........KaaaaaaafffffaaaaaaaK..........",
            "..........KKaaaaaaaaaaaaaaaKK...........",
            "............KaeaaaaaaaaaaaK.............",
            ".............KKKeaaaaaaKKK..............",
            "................KKKKKKK.................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x9AA3AD, "b": 0xF4A6B7, "c": 0x2B2B33, "d": 0xFFFFFF, "e": 0x7F8994, "f": 0x5A5F6B, "g": 0xD8DDE3]
    )

    static let camel = PixelSprite(
        rows: [
            "..............................KK........",
            ".............................KaaK.......",
            ".............................KaaKKKK....",
            "............................KKaaaaaaKK..",
            "...........................KaaaaaaaaaaK.",
            "...........................KaaaabaaaaaK.",
            "..........................KaaaaaaaaccccK",
            "...........................KaaaaaaacccK.",
            "...........................KaaaaaaacccK.",
            "...................KKKKKK...KKaaaaaaKK..",
            ".........KKKKK....KaaaaaaK..KaKKKKKK....",
            "........KaaaaaK..KaaaaaaaaK.KaaaaaK.....",
            ".......KaaaaaaaKKaaaaaaaaaaKKaaaaK......",
            "......KaaaaaaaaaKaaaaaaaaaaKaaaaaK......",
            "......KaaaaaaaaaKaaaaaaaaaaKaaaaK.......",
            ".....KaaaaaaaaaaaaaaaaaaaaaaaaaaK.......",
            ".....KaaaaaaaaaaaaaaaaaaaaaaaaaK........",
            ".....KaaaaaaaaaaaaaaaaaaaaaaKKK.........",
            ".....KaaaaaaaaaaaaaaaaaaaaaK............",
            "......KaaaaaaaaaaaaaaaaaaaaaK...........",
            ".....KaaaaaaaaaaaaaaaaaaaaaaaK..........",
            "..KKKaaaaaaaaaaaaaaaaaaaaaaaaaK.........",
            ".KccaaaaaaaaaaaaaaaaaaaaaaaaaaaK........",
            "..KccaaaaaaaaaaaaaaaaaaaaaaaaaaK........",
            "..KccaaaaaaaaaaaaaaaaaaaaaaaaaaK........",
            "...KccaaaaaaaaaaaaaccccccccccaaK........",
            "....KaaaaaaaaaaaaaccccccccccccK.........",
            ".....KaaaaaaaaaaaccccccccccccKK.........",
            "......KaaaaaaaaaacccccccccccKcK.........",
            "......KKKaaaaaaaaaccccccccKKccK.........",
            "......KccKKKaaaaaaaccccKKKKcccK.........",
            "......KcccK.KKKKKKKKKKKcK.KcccK.........",
            "......KcccK.KcccK...KcccK.KcccK.........",
            "......KcccK.KcccK...KcccK.KcccK.........",
            "......KcccK.KcccK...KcccK.KcccK.........",
            "......KdddK.KdddK...KdddK.KdddK.........",
            "......KdddK.KdddK...KdddK.KdddK.........",
            ".......KKK...KKK.....KKK...KKK..........",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xD9B382, "b": 0x2B2B33, "c": 0xB98B4E, "d": 0x8E6A3A]
    )

    static let rabbit = PixelSprite(
        rows: [
            "...........KKKK..........KKKK...........",
            "..........KaaaaK........KaaaaK..........",
            "..........KaaaaK........KaaaaK..........",
            ".........KaaaaaaK......KaaaaaaK.........",
            ".........KaabbaaK......KaabbaaK.........",
            ".........KaabbaaK......KaabbaaK.........",
            ".........KabbbbaK......KabbbbaK.........",
            ".........KabbbbaK......KabbbbaK.........",
            "........KaabbbbaaK....KaabbbbaaK........",
            "........KaabbbbaaK....KaabbbbaaK........",
            "........KaabbbbaaK....KaabbbbaaK........",
            "........KaabbbbaaK....KaabbbbaaK........",
            ".........KabbbbaK......KabbbbaK.........",
            ".........KabbbbaK..K...KabbbbaK.........",
            ".........KabbbKKKKKaKKKKKbbbbaK.........",
            ".........KaaKKaaaaaaaaaaaKKbaaK.........",
            ".........KKKaaaaaaaaaaaaaaaKKaK.........",
            ".........KaaaaaaaaaaaaaaaaaaaK..........",
            "........KaaaaaaaaaaaaaaaaaaaaaK.........",
            ".......KaaaaaaaaaaaaaaaaaaaaaaaK........",
            ".......KaaaaaaaaaaaaaaaaaaaaaaaK........",
            "......KaaaaaaaaaaaaaaaaaaaaaaaaaK.......",
            "......KaaaaaacccaaaaaaacccaaaaaaK.......",
            ".....KaaaaaaaaccaaaaaaaaccaaaaaaaK......",
            ".....KaaaaaaacccaaaaaaacccaaaaaaaK......",
            ".....KaaaaaaacccaaaaaaacccaaaaaaaK......",
            ".....KddaaaaaaaaaaeeeaaaaaaaaaaddK......",
            ".....KddabbbbbaaaaeeeaaaabbbbbaddK......",
            ".....KaabbbbbbbaaaeeeaaabbbbbbbaaK......",
            "......KdbbbbbbbaaadedaaabbbbbbbdK.......",
            "......KabbbbbbdddeeeeedddbbbbbbaK.......",
            ".......KabbbbddddedddeddddbbbbaK........",
            ".......KaaaaadddddddddddddaaaaaK........",
            "........KaaaadddddddddddddaaaaK.........",
            ".........KaaadddddddddddddaaaK..........",
            "..........KKaadddddddddddaaKK...........",
            "............KKaaaadddaaaaKK.............",
            "..............KKKKKaKKKKK...............",
            "...................K....................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xFFFFFF, "b": 0xF4A6B7, "c": 0x2B2B33, "d": 0xD8DDE3, "e": 0xE06C8B]
    )

    static let guitar = PixelSprite(
        rows: [
            "................KKKKKKKK................",
            "...............KaaaaaaaaK...............",
            "..............KaaaaaaaaaaK..............",
            ".............KbaaaaaaaaaabK.............",
            "..............KaaaaaaaaaaK..............",
            ".............KbaaaaaaaaaabK.............",
            "..............KaaaaaaaaaaK..............",
            "..............KaaaaaaaaaaK..............",
            "...............KaaaaaaaaK...............",
            "................KKKKKKKK................",
            "................KcbcbccK................",
            "................KdbdbddK................",
            "................KdbdbddK................",
            "................KcbcbccK................",
            "...............KKdbdbddK................",
            ".............KKeKdbdbddKKK..............",
            "............KeeeKcbcbccKeeK.............",
            "...........KeeeeKdbdbddKeeeK............",
            "...........KeeeeeKKKKKKeeeeK............",
            "..........KeeeeeeebebeeeeeeeK...........",
            "..........KeeeeeeebdbeeeeeeeK...........",
            "..........KeeffeedbabdeeeeeeK...........",
            "..........KeffffdaaaaadeeeeeK...........",
            "...........KfffddaaaaaddeeeK............",
            "..........KffffdaaaaaaadeeeeK...........",
            ".........KeffffddaaaaaddeeeeeK..........",
            "........KeefffffdaaaaadeeeeeeeK.........",
            ".......KeeeffffffdbabdeeeeeeeeeK........",
            ".......KeeeffffffebdbeeeeeeeeeeK........",
            ".......KeeeffffffebebeeeeeeeeeeK........",
            ".......KeeeffffffebebeeeeeeeeeeK........",
            ".......KeeeefffddddddddddeeeeeeK........",
            "........KeeeeffddddddddddeeeeeK.........",
            ".........KeeeeeeeeeeeeeeeeeeeK..........",
            "..........KeeeeeeeeeeeeeeeeeK...........",
            "...........KeeeeeeeeeeeeeeeK............",
            "............KKeeeeeeeeeeeKK.............",
            "..............KKKKKeKKKKK...............",
            "...................K....................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x2B2B33, "b": 0xD8DDE3, "c": 0x8E6A3A, "d": 0x6B4423, "e": 0x9A6A3A, "f": 0xD9A05B]
    )

    static let drum = PixelSprite(
        rows: [
            "........................................",
            "......KK.......................KK.......",
            ".....KaaK.....................KaaK......",
            ".....KaaaK...................KaaaK......",
            "......KaabK.................KbaaK.......",
            ".......KbbbK...............KbbbK........",
            "........KbbbK.............KbbbK.........",
            ".........KbbbK...........KbbbK..........",
            "..........KbbbK.........KbbbK...........",
            "...........KbbbK.......KbbbK............",
            "............KbbbK.....KbbbK.............",
            ".............KbbKKKKKKKbbK..............",
            ".........KKKKKKKcccccccKKKKKKK..........",
            "......KKKcccccccccccccccccccccKKK.......",
            "....KKcccccccdddddddddddddcccccccKK.....",
            "...KcccccdddddddddddddddddddddcccccK....",
            "...KccccdddddddddddddddddddddddccccK....",
            "...KccccdddddddddddddddddddddddcccceK...",
            "...KcccccdddddddddddddddddddddccccceK...",
            "...KeecccccccdddddddddddddccccccceeeK...",
            "...KeeeffcccccccccccccccccccccfffeeeK...",
            "...KeeefffffffffcccccccffffffffffeeeK...",
            "...KeeggffggffggffggffggffggffggfeeeK...",
            "...KeeeffffffffffffffffffffffffffeeeK...",
            "...KeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeK...",
            "...KeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeK...",
            "...KeeeffffffffffffffffffffffffffeeeK...",
            "...KeeeffffffffffffffffffffffffffeeeK...",
            "...KeeeffffffffffffffffffffffffffeeeK...",
            "...KeeggffggeeggeeggeeggeeggffggfeeeK...",
            "...KeeeeeeeeeeeeeeeeeeeeeeeeeeeefeeeK...",
            "...KeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeK...",
            "...KeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeK...",
            "...KeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeK...",
            "....KeeeeeeeeeeeeeeeeeeeeeeeeeeeeeKK....",
            ".....KKeeeeeeeeeeeeeeeeeeeeeeeeeKK......",
            ".......KKKKeeeeeeeeeeeeeeeeeKKKK........",
            "...........KKKKKKKKKKKKKKKKK............",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x6B4423, "b": 0xD9B382, "c": 0xF7E8C8, "d": 0xEBD6A8, "e": 0xB8322A, "f": 0xE24A3C, "g": 0xF2C230]
    )

    static let kitten = PixelSprite(
        rows: [
            "........................................",
            "............................K...........",
            ".......K...................KaK..........",
            "......KaK.................KaaK..........",
            ".....KaaaK...............KaaaaK.........",
            ".....KaabaK.............KaabaaK.........",
            ".....KabbbaK...........KaabbbaK.........",
            "....KaabbbbaK.KKKKKKKKKaabbbbaaK........",
            "....KaabbbbbaKaaaaaaaaaabbbbbaaK........",
            "....KabbbaaaaccaaccaaccaaaabbbaK........",
            "...KaaaaaaaaaccaaccaaccaaaaaaaaaK.......",
            "...KaaKKaaaaaccaaccaaccaaaaaKKaaK.......",
            "....KKKaaaaaaccaaccaaccaaaaaaKKK........",
            ".....KaaaaaaaaaaaaaaaaaaaaaaaaK.........",
            ".....KaaaaaaaaaaaaaaaaaaaaaaaaK.........",
            "....KaaaaaaaaaaaaaaaaaaaaaaaaaaK........",
            "....KaaaaaadddaaaaaaaadddaaaaaaK........",
            "....KaaaaadedddaaaaaadedddaaaaaK........",
            "....KaaaaadddddaaaaaadddddaaaaaK........",
            "....KcccaadddddaaaaaadddddaacccK........",
            "....KcccaaadddaaaaaaaadddaaacccK........",
            "....KaaaaaaaaaaffffffaaaaaaaaaaK........",
            "....KaaaaaaaaffffggffffaaaaaaaaK........",
            ".....KaaaaaaaffffggffffaaaaaaaK.........",
            ".....KaaaaaaffffffffffffaaaaaaK.........",
            "......KaaaaaaffffhhffffaaaaaaKKKKK......",
            ".......KaaaaafffhffhfffaaaaaKggiggK.....",
            "......KaKaaaaaaffffffaaaaaaKggggiggK....",
            "......KaaKKaaaaaaaaaaaaaaKKggiiiigggK...",
            ".....KaaaaaKKKaaaaaaaaKKKKgiiiiiiiiggK..",
            ".....KaaaaaaffKKKKKKKKaaaKgiiigggiiggK..",
            ".....KaaaaafffffffffaaaaaKgiiggggiiggK..",
            ".....KaaaaafffffffffaaaaaKiiiggggiiigK..",
            "......KaaaafffffffffaaaaKigiiggggiiggK..",
            "......KaaaafffffffffaaaaKggiiiiiiiiggK..",
            ".......KaaaafffffffaaaaK.KgggiiiigggK...",
            "........KKaaafffffaaaKK...KggggggggK....",
            "..........KKaaaaaaaKK......KggggggK.....",
            "............KKKKKKK.........KKKKKK......",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xF08A2E, "b": 0xF4A6B7, "c": 0xC96A1E, "d": 0x2B2B33, "e": 0xFFFFFF, "f": 0xF7E8C8, "g": 0xE06C8B, "h": 0x6B4423, "i": 0xFFD1DC]
    )

    static let glass = PixelSprite(
        rows: [
            ".......................KKK..............",
            "......................KaaaK.............",
            "......................KaaaK.............",
            "......................KaaaK.............",
            "......................KaaaK.............",
            "......................KaaaK.............",
            "......................KaaaK.............",
            ".....KKKKKKKKKKKKKKKKKKaaaKKKKKKKKKK....",
            "....KbbbbbbbbbbbbbbbbbKaaaKbbbbbbbbbK...",
            "....KbbbbbbbbbbbbbbbbbKaaaKbbbbbbbbbK...",
            "....KcccccccccccccccccKaaaKccccccccK....",
            "....KccccddcccccccccccKaaaKccccccccK....",
            "....KccccddccccccccccKeefKcccccccccK....",
            ".....KcccddccccccccccKeefKccccccccK.....",
            ".....KccccdccccccccccKeefKccccccccK.....",
            ".....KccccdccccccccccKeefKccccccccK.....",
            ".....KccccdccccccccccKeefKccccccccK.....",
            ".....KccccdccccccccccKeefKccccccccK.....",
            ".....KccccgggggggggggKeefKgggcccccK.....",
            ".....KgggggggggggggggKeefKgggggggcK.....",
            ".....KgggggggggggggggKeefKggggggghK.....",
            ".....KhhhhgggggggggggKeefKggghhhhhK.....",
            ".....KhhhhddhhhhhhhhhKeefKhhhhhhhhK.....",
            ".....KhhhhddhhhhhhhhhhKKKhiihhhhhhK.....",
            ".....KhhhhddhiihhhhhhhhhhhiihhhhhhK.....",
            "......KhhhddhiihhhhhhhhhhhhhhhhhhK......",
            "......KhhhddhhhhhhhhhhhhhhhhhhhhhK......",
            "......KhhhhdhhhhhhhhhhhhhhhhhhhhhK......",
            "......KhhhhdhhhhhhhhhhhiihhhhhhhhK......",
            "......KhhhhdhhhhhhhhhhhiihhhhhhhhK......",
            "......KhhhhdhhhhhiihhhhhhhhhhhhhhK......",
            "......KhhhhdhhhhhiihhhhhhhhhhhhhhK......",
            "......KhhhhhhhhhhhhhhhhhhhhhhhhhhK......",
            ".....KKhhhhhhhhhhhhhhhhhhhhhhhhhhKK.....",
            ".....KjKKKKKKKKKKKKKKKKKKKKKKKKKKjK.....",
            ".....KjjjjjjjjjjjjjjjjjjjjjjjjjjjjK.....",
            ".....KjjjjjjjjjjjjjjjjjjjjjjjjjjjjK.....",
            ".....KjjjjjjjjjjjjjjjjjjjjjjjjjjjjK.....",
            "......KKKKKKKKKKKKKKKKKKKKKKKKKKKK......",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xFF9C8C, "b": 0xE4F3FB, "c": 0xBFE3F5, "d": 0xFFFFFF, "e": 0xE24A3C, "f": 0xB8322A, "g": 0x5FB0E0, "h": 0x3596D4, "i": 0x9CD3F2, "j": 0xD8DDE3]
    )

    static let squirrel = PixelSprite(
        rows: [
            "........................................",
            ".............................KKKK.......",
            "...........................KKaaaaKK.....",
            "......KKK.........KKK.....KaaaaaaaaK....",
            ".....KaaaK.......KaaaK....KaaaaaaaaK....",
            "....KaaaaaK..K..KaaaaaK..KaaaaaaaaaaK...",
            "....KaabaKKKKaKKKKabaaK..KaaaaaaaaaaK...",
            "....KabKKaaaaaaaaaKKbaK..KaaaaaaaaaaK...",
            "....KaKaaaaaaaaaaaaaKaK.KaaaaaaaaaaaaK..",
            "....KKaaaaaaaaaaaaaaaKK.KaaaabbbbbaaaK..",
            "....KaaaaaaaaaaaaaaaaaK.KaaaabbbbbaaaK..",
            "....KaaaaacaaaaaaaaaaaKKaaaabbbbbbbaaaK.",
            "...KaaaaadccaaaaaaaaaaaKaaaabbbbbbbaaaK.",
            "...KaaaaacccaaaaaaaaaaaKaaaabbbbbbbaaaK.",
            "...KaaaaacccaaaaaaaaaaaKaaaabbbbbbbaaaK.",
            "...KaaeaaacaaaaaaaaaaaaKaaaabbbbbbbaaaK.",
            "...KaeeefffaaaaaaaaaaaaKaaaabbbbbbbaaaK.",
            "...KaaefffffaaaaaaaaaaaKaaaabbbbbbbaaaK.",
            "....KffffffffaaaaaaaaaKKaaaabbbbbbbaaaK.",
            "....KaffffffaaaaaaaaaaKKaaaabbbbbbbaaaK.",
            ".....KaffffaaaaaaaaaaKaaKaaabbbbbbbaaaK.",
            "....KaKaaaaaaaaaaaaaKaaaaKaabbbbbbbaaaK.",
            "....KaaKKaaaaaaaaaKKaaaaaKaabbbbbbbaaaK.",
            "...KaaaaaKKKKaKKKKfaaaaaaaKabbbbbbbaaaK.",
            "...KaaaaaafffKffffffKaaaaaKabbbbbbbaaaK.",
            "...KaaaaaffffffffffKeKaaaaKaabbbbbaaaK..",
            "...KaaaaafffffffffKKeKKaaaKaabbbbbaaaK..",
            "...KaaaaafffKKKffKggeggKaaKaaabbbaaaaK..",
            "...KaaaaaffKaaaKKKKgggggKaKaaaaaaaaaK...",
            "...KaaaaafKaaaaaKaaKggggKaKaaaaaaaaaK...",
            "...KaaaaafKaaaaKaaaaKggeKaKaaaaaaaaK....",
            "....KaaaaffKaaaKaaaaKeeeKK.KaaaaaaK.....",
            "....KaaaafffKKKfKaaKeeeeKK..KKKKKK......",
            ".....KaaaaffffffKKKeeeeeK...............",
            "......KaaaaffffffKeeeeeK................",
            ".......KaaaaaffffaKeeeK.................",
            "........KKaaaaaaaaaKKK..................",
            "..........KKKKKKKKKK....................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x9A6A3A, "b": 0xC08A57, "c": 0x2B2B33, "d": 0xFFFFFF, "e": 0x6B4423, "f": 0xF7E8C8, "g": 0xD9B382]
    )

    static let watermelon = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            ".KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.",
            "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
            "KaabccdddddeeeeeeeeeeeeeeeeedddddccbaaK.",
            "KaabccdddddeeeeeeeefeeeeeeeedddddccbaaK.",
            "KaabcccddddeeeeeeefffeeeeeeeddddcccbaaK.",
            "KaabbccddddfeeeeeefffeeeeeefddddccbbaaK.",
            ".KaabccddddffeeeeeefeeeeeeffddddccbaaK..",
            ".KaabccddddffeeeeeeeeeeeeeffddddccbaaK..",
            ".KaabbccddddfeeeeeeeeeeeeefddddccbbaaK..",
            "..KaabccdddddeeeeeeeeeeeeedddddccbaaK...",
            "..KaabbccdddddeeeeefeeeeedddddccbbaaK...",
            "..KaaabcccddddddeefffeeddddddcccbaaaK...",
            "...KaaabcccdddffddfffddffdddcccbaaaK....",
            "....KaabbcccddfffddfddfffddcccbbaaK.....",
            ".....KaabbccccfffdddddfffccccbbaaK......",
            ".....KaaabbbcccffdddddffcccbbbaaaK......",
            "......KKaaabbbcccccccccccbbbaaaKK.......",
            "........KaaaabbbbcccccbbbbaaaaK.........",
            ".........KaaaaaabbbbbbbaaaaaaK..........",
            "..........KKaaaaaaaaaaaaaaaKK...........",
            "............KKKaaaaaaaaaKKK.............",
            "...............KKKKKKKKK................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x2C7F44, "b": 0x39A85B, "c": 0xFFFFFF, "d": 0xE24A3C, "e": 0xF06A5C, "f": 0x2B2B33]
    )

    static let turtle = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "...........KKKKKKKKKKKK.................",
            "........KKKaaabbaabbaaaKKK..............",
            ".......KaaaaabaaaaaabaaaaaK.............",
            "......KaaaaaabaaaaaabaaaaaaK............",
            ".....KaaaaaaabaaaaaabaaaaaaaK...........",
            "....KaaaabbaabaaaaaabaabbaaaaK..........",
            "...KaaabbaabbabbaabbabbaabbaaaKKKKK.....",
            "..KaaaabaaaabaabbbbaabaaaabaaaaKcccKK...",
            ".KKaaaabaaaabaaaaaaaabaaaabaaaaKcccccK..",
            "KcKaaaabaaaabaaabbaaabaaaabaaaaKdcccccK.",
            ".KKaaaabaaaababbaabbabaaaabaaaaKdcccccK.",
            ".KKaaaabbaabbabaaaababbaabbaaaaKcccccccK",
            "..KaaaaaabbaaabaaaabaaabbaaaaaaKccccccK.",
            "..KaaaaaaaaaaabaaaabaaaaaaaaaaaKcccbbbK.",
            "..KccccccccccccccccccccccccccccKcccccK..",
            "...KccccccccccccccccccccccccccKccccKK...",
            "....KccccccccccccccccccccccccK.KKKK.....",
            ".....KaaaaaaaaaaaaaaaaaaaaaaK...........",
            "....KcKaaaaaaaaaaaaaaaaaaaaKcK..........",
            "....KccKaaaaaaaaaaaaaaaaaaKccK..........",
            "....KcccKKKaaaaaaaaaaaaKKKcccK..........",
            ".....KcccccKKKKKKKKKKKKcccccK...........",
            "......KccccK..........KccccK............",
            ".......KKKK............KKKK.............",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x39A85B, "b": 0x2C7F44, "c": 0x8DD16B, "d": 0x2B2B33]
    )

    static let eyeglasses = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            ".K....................................K.",
            "KaK..................................KaK",
            "KaaK................................KaaK",
            "KaaK................................KaaK",
            "KaaK......KKK..............KKK......KaaK",
            ".KaaK..KKKaaaKKK........KKKaaaKKK..KaaK.",
            ".KaaK.KaaaaaaaaaK......KaaaaaaaaaK.KaaK.",
            ".KaaKKaaaabbbaaaaK....KaaaabbbaaaaKKaaK.",
            "..KaKaaabbbbbbbaaaK..KaaabbbbbbbaaaKaK..",
            "..KKaabccccbbbbbbaaKKaabccccbbbbbbaaKK..",
            "..KaaabccccbbbbbbaaKaaabccccbbbbbbaaaK..",
            "..KaabbccccbbbbbbbaKaabbccccbbbbbbbaaK..",
            "..KaabbbbbbbbbbbbbaKaabbbbbbbbbbbbbaaK..",
            "..KaabbbbbbbbbbbbbaKaabbbbbbbbbbbbbaaK..",
            "..KaabbbbbbbbbbbbbaKaabbbbbbbbbbbbbaaK..",
            "..KaabbbbbbbbbbbbbaKaabbbbbbbbbbbbbaaK..",
            "..KaaabbbbbddddbbaaKaaabbbbbddddbbaaaK..",
            "...KaabbbbbddddbbaaKKaabbbbbddddbbaaK...",
            "....KaaabbbbbbbaaaK..KaaabbbbbbbaaaK....",
            ".....KaaaabbbaaaaK....KaaaabbbaaaaK.....",
            "......KaaaaaaaaaK......KaaaaaaaaaK......",
            ".......KKKaaaKKK........KKKaaaKKK.......",
            "..........KKK..............KKK..........",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x2B2B33, "b": 0xBFE3F5, "c": 0xFFFFFF, "d": 0xE4F3FB]
    )

    static let cat = PixelSprite(
        rows: [
            "........................................",
            "......K.....................K...........",
            ".....KaK...................KaK..........",
            ".....KaaK.................KaaK..........",
            ".....KaaaKK.............KKaaaK..........",
            ".....KabbaaK...........KaabbaK..........",
            ".....KabbbaaK.KKKKKKK.KaabbbaK..........",
            "....KaabbbbaaKaaaaaaaKaabbbbaK..........",
            "....KaabbbbaaccaacaaccaabbbbaaK.........",
            "....KaabbaaaaccaacaaccaaaabbaaK.........",
            "....KaabaaaaaccaacaaccaaaaabaaK.........",
            "....KaaaaaaaaccaacaaccaaaaaaaaK.........",
            "....KaaaaaaaaaaaacaaaaaaaaaaaaK.........",
            "....KaaaaaaaaaaaaaaaaaaaaaaaaaK.........",
            "....KaaaaaadddaaaaaaadddaaaaaaK.........",
            "....KaaaaaaeddaaaaaaaeddaaaaaaK.........",
            "....KaaaaadddddaaaaadddddaaaaaK.........",
            "...KaaaaaadddddaaaaadddddaaaaaaK........",
            "....KaaaaaadddaaaaaaadddaaaaaaK.........",
            "....KaaaaaadddaaaaaaadddaaaaaaK.........",
            "....KaaaaaaaaaaafffaaaaaaaaaaaK.........",
            "....KggggggaaaaafffaaaaaggggggKKKK......",
            ".....KaaaaaaaaaafcfaaaaaaaaaaKKaaaK.....",
            "......KgggaaaaaaacaaaaaaagggKKaaaaaK....",
            ".......KaaaaaaacccccaaaaaaaKKaaaKaaaK...",
            "........KaaaaaaaaaaaaaaaaaK.KaaK.KaaK...",
            "........KKKaaaaaaaaaaaaaKKKKaaaK.KaaaK..",
            ".......KaaaKKKaaaaaaaKKKaaaKaaaK.KaaaK..",
            "......KaaaaaaaKKKKKKKaaaaaaaKaaK.KaaaK..",
            ".....KaaaaaaagggggggggaaaaaaaKaK.KaaaK..",
            ".....KaaaaaagggggggggggaaaaaaKK..KaaaK..",
            ".....KaaaaaagggggggggggaaaaaaK...KaaaK..",
            ".....KaaaaaagggggggggggaaaaaaK...KaaaK..",
            ".....KaaaaaagggggggggggaaaaaaK...KaaaK..",
            "......KaaaaagggggggggggaaaaaK....KaaK...",
            ".......KaaaagggggggggggaaaaK....KaaaK...",
            "........KaaaagggggggggaaaaK.....KaaK....",
            ".........KKaaaagggggaaaaKK......KaK.....",
            "...........KKaaaaaaaaaKK.........K......",
            ".............KKKKKKKKK..................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x9AA3AD, "b": 0xF4A6B7, "c": 0x5A5F6B, "d": 0x2B2B33, "e": 0xFFFFFF, "f": 0xE06C8B, "g": 0xD8DDE3]
    )

    static let spinningTop = PixelSprite(
        rows: [
            ".................KKKKKK.................",
            "................KaaaaaaK................",
            "................KabaaaaK................",
            "................KabaaaaK................",
            "................KabaaaaK................",
            "................KabaaaaK................",
            "................KabaaaaK................",
            "................KabaaaaK................",
            "................KabaaaaK................",
            "................KKKKKKaK................",
            "..............KKKcccccKKK...............",
            "...........KKKcccccccccccKKK............",
            "........KKKddcccccccccccccddKKK.........",
            "......KKddddddcccccccccccddddddKK.......",
            ".....KddddeeeddddcccccdddddddddddK......",
            "....KddddeeeeeddddddddddddddddddddK.....",
            "...KddddeeeeeddddddddddddddddddddddK....",
            "...KdddddeeedddddddddddddddddddddddK....",
            "...KdddddddddddddddddddddddddddddddK....",
            "....KdddddddddddddddddddddddddddddKK....",
            "...KffffffffffffffffffffffffffffffffK...",
            "...KffffffffffffffffffffffffffffffffK...",
            "...KffffffffffffffffffffffffffffffffK...",
            "....KggggggggggggggggggghhhhhhhhhhKK....",
            ".....KgggggggggggggggggghhhhhhhhhK......",
            "......KgggggggggggggggghhhhhhhhhK.......",
            ".......KggggggggggggggghhhhhhhhK........",
            "........KgggggggggggggghhhhhhhK.........",
            ".........KggggggggggggghhhhhhK..........",
            "..........KKgggggggggghhhhhKK...........",
            "............KggggggggghhhhK.............",
            ".............KgggggggghhhK..............",
            "..............KggggggghhK...............",
            "...............KggggghhK................",
            "................KgggghK.................",
            ".................KaaaaK.................",
            ".................KaaaaK.................",
            ".................KaaaaK.................",
            "..................KKKK..................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x6B4423, "b": 0x8E6A3A, "c": 0x5FB0E0, "d": 0x3596D4, "e": 0xFFFFFF, "f": 0xF2C230, "g": 0xE24A3C, "h": 0xB8322A]
    )

    static let pillow = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "...KKK............................KKK...",
            "..KaaaK...KKKKKKKKKKKKKKKKKKK....KaaaK..",
            ".KaaaaaKKKbbbbbbbbbbbbbbbbbbbKKKKaaaaaK.",
            ".KaaaKKbbbbbbbbbbbbbbbbbbbbbbbbbbKKaaaK.",
            ".KaaKbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbKaaK.",
            "..KaKbbbccccccccccccccccccccccccbbbKaK..",
            "...KbbbcccddddcbbbccbbbccbbbccbccbbbK...",
            "...KbbccdddddddbbbccbbbccbbbccbbccbbK...",
            "...KbbcddddddddbbbccbbbccbbbccbbbcbbK...",
            "...KbbcddddddddbbbccbbbccbbbccbbbcbbK...",
            "...KbbcdddddddcbbbccbbbccbbbccbbbcbbK...",
            "...KbbcbddddbccbbbccbbbccbbbccbbbcbbK...",
            "...KbbcbccbbbccbbbccbbbccbbbccbbbcbbK...",
            "...KbbcbccbbbccbbbccbbbccbbbccbbbcbbK...",
            "...KbbcbccbbbccbbbccbbbccbbbccbbbcbbK...",
            "...KbbcbccbbbccbbbccbbbccbbbccbbbcbbK...",
            "...KbbcbccbbbccbbbccbbbccbbbccbbbcbbK...",
            "...KbbcbccbbbccbbbccbbbccbbbccbbbcbbK...",
            "...KbbcbccbbbccbbbccbbbccbbbccbbbcbbK...",
            "...KbbcbccbbbccbbbccbbbccbbbccbbbcbbK...",
            "...KbbccccbbbccbbbccbbbccbbbccbbccbbK...",
            "...KbbbccbbbbbbbbbbbbbbbbbbbbbbccbbbK...",
            "..KaKbbbccccccccccccccccccccccccbbbKaK..",
            ".KaaKbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbKaaK.",
            ".KaaaKKbbbbbbbbbbbbbbbbbbbbbbbbbbKKaaaK.",
            ".KaaaaaKKKbbbbbbbbbbbbbbbbbbbKKKKaaaaaK.",
            "..KaaaK...KKKKKKKKKKKKKKKKKKK....KaaaK..",
            "...KKK............................KKK...",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xF2C230, "b": 0xBFE3F5, "c": 0x9CCBE8, "d": 0xFFFFFF]
    )

    static let ostrich = PixelSprite(
        rows: [
            "...........................KK...........",
            ".........................KKaaKK.........",
            "........................KaaaaaaK........",
            ".......................KaabcaaaaK.......",
            "......................KaaaccaaaddKKKK...",
            "......................KaaaccaaaddddddK..",
            ".......................KaaaaaaaddKKKK...",
            "........................KaaaaaaKK.......",
            "........................KKKaaKK.........",
            "........................KaaKKK..........",
            "........................KaaaK...........",
            "...........KKKKKKKK....KaaaaK...........",
            ".........KKbbbbbbbbKK..KaaaaK...........",
            ".......KKbbbbbbbbbbbbKKKaaaaK...........",
            "......KcccbbbbbbbbbbbbbKaaaaK...........",
            ".....KccccbbbbbbbbbbbbbKaaaK............",
            "....KcccccbbbbbbbbbbbbKaaaaK............",
            "...KccccccbbbbbbbbbbbbKaaaaK............",
            "...KccccccbbbbbbbbbbbbKaaaaK............",
            "...KccccccbbbbbbbbbbbbKaaaK.............",
            "...KccccccbbbbbbbbbbbKaaaaK.............",
            "...KcccccccbbbbbbbbbbKaaKKK.............",
            "...KccccccccbbbbbbbbbbKKbbK.............",
            "...KccccccccbbbbeeeeeebbbbK.............",
            "...KbbccccccbbbeeeeeeeebbbK.............",
            "....KbccccccbbeeeeeeeeeebK..............",
            ".....KbccccbbbeeeeeeeeeeK...............",
            "......KbbbbbbbbeeeeeeeeK................",
            ".......KKbbbbbbbeeeeeKK.................",
            ".........KKbbbbbbbbKK...................",
            "...........KKKKKKKKK....................",
            "...........KaK...KaK....................",
            "..........KaaK...KaaK...................",
            "..........KaaK...KaaK...................",
            "..........KaaK...KaaK...................",
            "..........KaaK...KaaK...................",
            "..........KaKK....KaKK..................",
            "..........KaaaK...KaaaK.................",
            "...........KKK.....KKK..................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xE8B4A0, "b": 0xFFFFFF, "c": 0x2B2B33, "d": 0xF08A2E, "e": 0xD8DDE3]
    )

    static let handFan = PixelSprite(
        rows: [
            "...................K....................",
            "..............KKKKKaKKKKK...............",
            "............KKaaaaabaaaaaKK.............",
            "..........KKaaaaaabbbaaaaaaKK...........",
            ".........KaaaaaaaaabaaaaaaaaaK..........",
            "........KaaaaaaaaaaaaaaaaaaaaaK.........",
            ".......KabbaaaacccccccccaaaabbaK........",
            "......KaabbaacccccccccccccaabbaaK.......",
            ".....KaaaaaacccccccccccccccaaaaaaK......",
            ".....KaaaaacccccccccccccccccaaaaaK......",
            "....KaaaaaccccccccaaaccccccccaaaaaK.....",
            "....KaaaaaccccccaaaaaaaccccccaaaaaK.....",
            "...KaaaaaccccccaaaaaaaaaccccccaaaaaK....",
            "...KaaaaacccccaaaaaaaaaaacccccaaaaaK....",
            "...KaaaaacccccaaaaaaaaaaacccccaaaaaK....",
            "...KabbaacccccaaaaaaaaaaacccccaabbaK....",
            "...KabbaacccccaaaaaaaaaaacccccaabbaK....",
            "...KaaaaacccccaaaaaaaaaaacccccaaaaaK....",
            "...KaaaaacccccaaaaaaaaaaacccccaaaaaK....",
            "...KaaaaaccccccaaaaaaaaaccccccaaaaaK....",
            "....KaaaaaccccccaaaaaaaccccccaaaaaK.....",
            "....KaaaaaccccccccaaaccccccccaaaaaK.....",
            ".....KaaaaacccccccccccccccccaaaaaK......",
            ".....KaaaaaacccccccccccccccaaaaaaK......",
            "......KaabbaacccccccccccccaabbaaK.......",
            ".......KabbaaaacccccccccaaaabbaK........",
            "........KaaaaaaaaaaaaaaaaaaaaaK.........",
            ".........KaaaaaaaaabaaaaaaaaaK..........",
            "..........KKaaaaaabbbaaaaaaKK...........",
            "............KKaaaaabaaaaaKK.............",
            "..............KKKKKaKKKKK...............",
            ".................KdKddK.................",
            ".................KddddK.................",
            ".................KddddK.................",
            ".................KddddK.................",
            ".................KddddK.................",
            ".................KddddK.................",
            ".................KddddK.................",
            "..................KKKK..................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xE24A3C, "b": 0xF2C230, "c": 0xFFFFFF, "d": 0xD9B382]
    )

    static let crocodile = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            ".......KK..KKKK.KKKK.KKK..KKK...........",
            "......KaaKKaaaaKaaaaKbbbKKbbbK..........",
            ".....KaaaaKaaaaKaaaabcccbbcccbK.........",
            "...KKKaaaabaaaabaaaabcdcbbcdcbK.........",
            "..KbbKaaaabaaaabaaaabcccbbcccbKKK.......",
            ".KbbbbbaabbbbbbbbbbbbbbbbbbbbbbbbKKK....",
            "KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK...",
            "KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbK..",
            ".KbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdK.",
            ".KbbbbbbbbbbbbbbbbbbbbbbbbbbebbebbebbbbK",
            "..KbbbfffffffffffffffffffKKKKKKKKKKKKKK.",
            "...KbbfffffffffffffffffffffffeffeffefK..",
            "....KKKfffffffffffffffffffffffffffffK...",
            "......KKKbbbbbbbbbbbbbbbbKKbbbbbbKKK....",
            ".....KaaaKKKKKKKKKKKKKKKKK.KKKKKK.......",
            "....KaaaaaaaaK...KaaaaaaaaK.............",
            "....KaaaaaaaaK...KaaaaaaaaK.............",
            ".....KaaaaaaK.....KaaaaaaK..............",
            "......KaaaaK.......KaaaaK...............",
            ".......KKKK.........KKKK................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x2C7F44, "b": 0x39A85B, "c": 0xF2C230, "d": 0x2B2B33, "e": 0xFFFFFF, "f": 0x8DD16B]
    )

    static let boat = PixelSprite(
        rows: [
            "........................................",
            "....................KK..................",
            "...................KaaKKKK..............",
            "..................KKaaaaaaK.............",
            "..................KKaaKKKK..............",
            "..................KbKK..................",
            "..................KbKcK.................",
            "..................KbKdcK................",
            "..................KbKddcK...............",
            "..................KbKdddK...............",
            ".................KKbKdddcK..............",
            "................KeKbKddddcK.............",
            "...............KeeKbKdddddK.............",
            "..............KeeeKbKddddddK............",
            "..............KeeeKbKddddddcK...........",
            ".............KeeeeKbKdddddddcK..........",
            "............KeeeeeKbKddddddddK..........",
            "...........KeeeeeeKbKddddddddcK.........",
            "..........KeeeeeeeKbKdddddddddcK........",
            "..........KeeeeeeeKbKddddddddddK........",
            ".........KeeeeeeeeKbKdddddddddddK.......",
            "........KeeeeeeeeeKbKdddddddddddcK......",
            ".......KeeeeeeeeeeKbKddddddddddddcK.....",
            "........KKKKKKKKKKKbbKKKKKKKKKKKKK......",
            "...KKKKKKKKKKKKKKKKbbKKKKKKKKKKKKKKKK...",
            "..KfffffffffffffffKbbKfffffffffffffffK..",
            "..KffffffffffffffffKKffffffffffffffffK..",
            "...KKggggggggggggggggggggggggggggggKK...",
            "....KgggggggggggggggggggggggggggggK.....",
            ".....KgggggggggggggggggggggggggggK......",
            "......KggggggggggggggggggggggggggK......",
            ".......KggggggggggggggggggggggggK.......",
            "..KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
            ".KhhiihhhhhiihhhhhiihhhhhiihhhhhiihhhhK.",
            ".KhhhhihhhhhhihhhhhhihhhhhhihhhhhhihhhK.",
            ".KhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhK.",
            ".KhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhK.",
            ".KhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhK.",
            "..KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xE24A3C, "b": 0x6B4423, "c": 0xD8DDE3, "d": 0xFFFFFF, "e": 0xF2D24B, "f": 0x8B4513, "g": 0xB5651D, "h": 0x4AA8E0, "i": 0xBFE3F5]
    )

    static let leek = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "..........K.................K...........",
            "........KKaK...............KaKK.........",
            ".......KaaaaK.............KaaaaK........",
            "......KaabaaaK...........KaaabaaK.......",
            ".......KaabaaK....KKKK...KaaabaK........",
            ".......KaaabaaK..KaaaaK.KaaabaaK........",
            "........KaabaaaK.KaaaaKKaaabaaK.........",
            "........KaaabaaK.KaaaaKaaaabaaK.........",
            ".........KaabaaaKaaaaaaaaabaaK..........",
            ".........KaaabaaaaaaaaaaaabaaK..........",
            "..........KaaabaaaaaaaaaabaaK...........",
            "...........KaabaaaaaaaaaabaK............",
            "...........KaaabaaaaaaaabaaK............",
            "............KaaabaaaaaabaaK.............",
            "............KaaabaaaaaabaaK.............",
            ".............KaaaaaaaaaaaK..............",
            ".............KaaaaaaaaaaaK..............",
            "..............KaKKKKKKKaKK..............",
            "..............KKcddddddKdK..............",
            "..............KdcddddddddK..............",
            "..............KdcddddddddK..............",
            "..............KdcddddddddK..............",
            "..............KdcddddddddK..............",
            "..............KdcddddddddK..............",
            "..............KdcddddddddK..............",
            "..............KdcddddddddK..............",
            "..............KdcddddddddK..............",
            "..............KdcddddddddK..............",
            "..............KeeeeeeeeeeK..............",
            "..............KeeeeeeeeeeK..............",
            "..............KeeeeeeeeeeK..............",
            "..............KeeeeeeeeeeK..............",
            "..............KfeeffeefeeK..............",
            "..............KfKKffKKfKK...............",
            "..............KfKKffKKfK................",
            "...............K..KK..K.................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x39A85B, "b": 0x2C7F44, "c": 0xFFFFFF, "d": 0xF4F7E8, "e": 0xD9DFC4, "f": 0xBFA98A]
    )

    static let ball = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "................KKKKKKK.................",
            ".............KKKaabbbaaKKK..............",
            "...........KKaaaaabbbaaaaaKK............",
            "..........KaaaaaabbbbbaaaaaaK...........",
            "........KKcaaaaaabbbbbaaaaaaaKK.........",
            ".......KcccccaaabbbbbbbaaaaaaaaK........",
            "......KaccccccaabbbbbbbaaaaaaaaaK.......",
            "......KaccccccaabbbbbbbaaaaaaaaaK.......",
            ".....KaaccccccaabbbbbbbaaaaaaaaaaK......",
            "....KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.....",
            "....KdddddddddabbbbbbbbbadddddddddK.....",
            "...KdddddddddaabbbbbbbbbaadddddddddK....",
            "...KdddddddddaabbbbbbbbbaadddddddddK....",
            "...KdddddddddaabbbbbbbbbaadddddddddK....",
            "...KbbbbbbbbbaabbbbbbbbbaabbbbbbbbbK....",
            "...KbbbbbbbbbaabbbbbbbbbaabbbbbbbbbK....",
            "...KbbbbbbbbbaabbbbbbbbbaabbbbbbbbbK....",
            "...KbbbbbbbbbaabbbbbbbbbaabbbbbbbbbK....",
            "...KbbbbbbbbbaabbbbbbbbbaabbbbbbbbbK....",
            "...KdddddddddaabbbbbbbbbaadddddddddK....",
            "...KdddddddddaabbbbbbbbbaadddddddddK....",
            "...KdddddddddaabbbbbbbbbaadddddddddK....",
            "...KdddddddddaabbbbbbbbbaadddddddddK....",
            "....KaaaaaaaaaabbbbbbbbbaaaaaaaaeeK.....",
            "....KaaaaaaaaaaabbbbbbbaaaaaaaaeeeK.....",
            ".....KaaaaaaaaaabbbbbbbaaaaaaaaeeK......",
            "......KaaaaaaaaabbbbbbbaaaaaaaeeK.......",
            "......KaaaaaaaaabbbbbbbaaaaaaeeeK.......",
            ".......KaaaaaaaabbbbbbbaaaaaeeeK........",
            "........KKaaaeaaabbbbbaaaaeeeKK.........",
            "..........KaaaeeabbbbbaaeeeeK...........",
            "...........KKaaeeebbbeeeeeKK............",
            ".............KKKeebbbeeKKK..............",
            "................KKKKKKK.................",
            "........................................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xE24A3C, "b": 0xF2D24B, "c": 0xFFFFFF, "d": 0xFF7A6B, "e": 0xB8322A]
    )

    static let mushroom = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "...................K....................",
            ".............KKKKKKaKKKKKK..............",
            "..........KKKaaaaaabaaaaaaKKK...........",
            "........KKaaaaaaabbbbbaaaaaaaKK.........",
            ".......KaaaaaaaabbbbbbbaaaaaaaaK........",
            ".....KKaaaaaaaaabbbbbbbaaaaaaaaaKK......",
            "....KaaaaaaaaaaabbbbbbbaaaaaaaaaaaK.....",
            "....KaaaaaaaaaaaabbbbbaaaaaaaaaaaaK.....",
            "...KaaaabbaaaaaaaaabaaaaaaaabbaaaaaK....",
            "..KaaabbbbbbaaaaaaaaaaaaaabbbbbbaaaaK...",
            "..KaaabbbbbbaaaaaaaaaaaaaabbbbbbaaacK...",
            "..KaaabbbbbbaaaaaaaaaaaaaabbbbbbaaaaK...",
            "..KaaabbbbbbaaaaaaaaaaaaaabbbbbbaaaaK...",
            "..KaaaaabbaaaaaaaaaaaaaaaaaabbaaaaaaK...",
            "..KaaaaaaaaaabbaaaaaaaaaaaaaaaaaaaaaK...",
            "..KaaaaaaaaabbbbaaaaaaabbbbaaaaaaaaaK...",
            "..KaaaaaaaaabbbbaaaaaaabbbbaaaaaaaaaK...",
            "...KaaaaaaaaabbaaaaaaaabbbbaaaaaaaaK....",
            "....KaaaaaaaaaaaaaaaaaaaaaaaaaaaaaK.....",
            "....KdddddddddddddddddddddddddddddK.....",
            ".....KKdddddddddddddddddddddddddKK......",
            ".......KKKKKKKKKKKKKKKKKKKKKKKKK........",
            "...........KeeeeffffffffffffK...........",
            "...........KeeeeffffffffffffK...........",
            "...........KeeeeffffffffffffK...........",
            "...........KeeeeffffffffffffK...........",
            "...........KeeeeffffffffffffK...........",
            "...........KeeeeffffffffffffK...........",
            "...........KeeeeffffffffffffK...........",
            "...........KeeeeffffffffffffK...........",
            "...........KeeeeffffffffffffK...........",
            "...........KeeeeffffffffffffK...........",
            "...........KeeeeffffffffffffK...........",
            "...........KeeeefffffffffffK............",
            "............KKKKKKKKKKKKKKK.............",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xE24A3C, "b": 0xFFFFFF, "c": 0xB8322A, "d": 0xC9B18A, "e": 0xE3D2AC, "f": 0xF6E7C8]
    )

    static let horse = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "..................KKKK..................",
            ".................KaaKbK.................",
            "................KaaaKbKK......K.........",
            "...............KaaaKbcbKK..KKKaK........",
            "...............KaaaKbcbKKKKaaaaK........",
            "................KaKbccbbKaaaaaaK........",
            "..............KKKKKbcccbKaaaaaaaK.......",
            "............KKbbbbbbcccbKaaaaaaaK.......",
            "...........KbbbbbbbbbbbbbKaaaaaaK.......",
            "..........KbbbbbbbbbbbbbKaaaaaaaK.......",
            ".........KbbbbbbbbbbbbbbbKaaaKaaK.......",
            "........KbbbbbbbbbbbbbbbbbKaKbKaK.......",
            ".......KbbbbbddbbbbbbbbbbbbKbbKaK.......",
            ".......KbbbbdeddbbbbbbbbbbbKbbKaaK......",
            ".......KbbbbddddbbbbbbbbbbbKbbKaaK......",
            ".......KbbbbddddbbbbbbbbbbbKbbKaaK......",
            ".......KbbbbbddbbbbbbbbbbbbKbbKaaK......",
            "......KKbbbbbbbbbbbbbbbbbbbKbbbKaK......",
            ".....KbbbbbbbbbbbbbbbbbbbbKbbbbKaK......",
            "....KbbbbbbbbbbbbbbbbbbbbKbbbbbKaaK.....",
            "...KcbbbbbbbbbbbbbbbbbbbKbbbbbbKaaK.....",
            "..KcccbbbbbbbbbbbbbbbbbKbbbbbbbKaaK.....",
            "..KccfffbbbbbbbbbbbbbKKbbbbbbbbKaaK.....",
            "..KccfffcbbbbbbcKKKKKbbbbbbbbbbKaaK.....",
            "..KcccccccccccccK.KbbbbbbbbbbbbKaaK.....",
            "..KcccccccccccccK.KbbbbbbbbbbbbKaaaK....",
            "...KcccccccccccK..KbbbbbbbbbbbbKaaaK....",
            "....KcfffffcccK....KbbbbbbbbbbbKaaaK....",
            ".....KcccccccK.....KbbbbbbbbbbbKaaaK....",
            "......KKKKKKK......KbbbbbbbbbbbbKaaK....",
            "...................KbbbbbbbbbbbbKaaK....",
            "...................KbbbbbbbbbbbbKaaK....",
            "...................KbbbbbbbbbbbbKaaaK...",
            "...................KbbbbbbbbbbbbKaaaK...",
            "...................KbbbbbbbbbbbbKaaaK...",
            "....................KKKKKKKKKKKKKKKK....",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x4A2A12, "b": 0xB5651D, "c": 0xE0A97A, "d": 0x2B2B33, "e": 0xFFFFFF, "f": 0x6B4423]
    )

    static let deer = PixelSprite(
        rows: [
            "........................................",
            "............K..K.......K..K.............",
            "...........KaKKaK.....KaKKaK............",
            "..........KaaaaaK.....KaaaaaK...........",
            "......KKK.KaaaaK.......KaaaaK.KKK.......",
            ".....KaaaKKaaKK.........KKaaKKaaaK......",
            "......KaaaKaaK...........KaaKaaaK.......",
            ".......KaaaaaK...........KaaaaaK........",
            "........KKaaaK...........KaaaKK.........",
            ".........KaaK......K......KaaK..........",
            ".........KaaK..KKKKbKKKK..KaaK..........",
            ".........KaaKKKbbbbcbbbbKKKaaK..........",
            ".........KaaKbbbbbbcbbbbbbKaaK..........",
            "......KKKKKKbbbccbbbbbccbbbKKKKKK.......",
            "....KKbbbbKbbbbccbbbbbccbbbbKbbbbKK.....",
            "...KbbbbdKbbbbbbbbbbbbbbbbbbbKdbbbbK....",
            "..KbbbdddKbbbbbbbbbbbbbbbbbbbKdddbbbK...",
            "..KbbdddKbbbbbebbbbbbbbbebbbbbKdddbbK...",
            "..KbbbdbKbbbbceebbbbbbbceebbbbKbdbbbK...",
            "..KbbbbbKbbbbeeebbbbbbbeeebbbbKbbbbbK...",
            "...KKKKKKbbbbeeebbbbbbbeeebbbbKKKKKK....",
            "........KbbbbbebbbbbbbbbebbbbbK.........",
            "........KbbbbbbbbbbbbbbbbbbbbbK.........",
            "........KbbbccbbdddddddbbccbbbK.........",
            "........KbbbccbdddddddddbccbbbK.........",
            ".........KbbbbdddKKKKKdddbbbbK..........",
            ".........KbbbddddKKKKKddddbbbK..........",
            "..........KbbddddKKKKKddddbbK...........",
            "...........KbddddddfddddddbK............",
            "............KddddddfddddddK.............",
            ".............KdddfffffdddK..............",
            "..............KdddddddddK...............",
            "...............KdddddddK................",
            "................KKKKKKK.................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0x7A4B1F, "b": 0xC98B4A, "c": 0xFFFFFF, "d": 0xF3D9B1, "e": 0x2B2B33, "f": 0x6B4423]
    )

    static let cow = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........K.....................K.........",
            ".......KaK...................KaK........",
            ".......KaaK.................KaaK........",
            ".......KaaK.................KaaK........",
            ".......KaaaK....KKKKKKK....KaaaK........",
            ".......KaaaaKKKKaaaaaaaKKK.KaaaK........",
            ".......KaaaKKbbaaaaaaaaabbKKaaaK........",
            ".......KaaKccccbaaaaaaabbbbbKaaK........",
            "........KKccccccbaaaaabbbbbbbKK.........",
            "........KcccccccbbbbbbbbbbbbbbK.........",
            ".......KccccccccbbbbbbbbbbbbbbbK........",
            "...KKKKKccccccccbbbbbbbbbbbbbbbKKKKK....",
            "..KdddKcccccccccbbbbbbbbbbbbbbbbKdddK...",
            ".KdddeKccccccccbbbbbbbbbbcbbbbbbKedddK..",
            "KddeeKbccccccbccbbbbbbbbbccccccbbKeeddK.",
            "KddeeKbbbcccbcccbbbbbbbbccccccccbKeeddK.",
            "KdddeKbbbbbbbcccbbbbbbbbcccccccccKedddK.",
            "KddddKbbbbbbbbcbbbbbbbbbbccccccccKddddK.",
            ".KKKKKbbbbbbbbbbbbbbbbbbcccccccccKKKKK..",
            ".....KbbbbbbbbbbfffffffbcccccccccK......",
            "......KbbbbbbfffffffffffffccccccK.......",
            "......KbbbbbffffgggggggffffcccccK.......",
            ".......KbbbfffgggggggggggfffcccK........",
            ".......KbbfffgggggggggggggfffcbK........",
            "........KbffffgggggggggggffffbK.........",
            ".........KfffffKKKgggKKKfffffK..........",
            ".........KfffffKKKfffKKKfffffK..........",
            "..........KfffffffffffffffffK...........",
            "...........KfffffffffffffffK............",
            "............KfffffffffffffK.............",
            ".............KKKfffffffKKK..............",
            "................KKKKKKK.................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xE8D9A8, "b": 0xFFFFFF, "c": 0x2B2B33, "d": 0xF3D9B1, "e": 0xF4A6B7, "f": 0xF7A8B8, "g": 0xFFC9D4]
    )

    static let bell = PixelSprite(
        rows: [
            "........................................",
            "..................KKK...................",
            "................KKaaaKK.................",
            "...............KaaaaaaaK................",
            "...............KaaKKKaaK................",
            "..............KaaK...KaaK...............",
            "..............KaaK...KaaK...............",
            "...............KaaKKKaaK................",
            "...............KKKKKKKKK................",
            ".............KKKaaaaaaaKKK..............",
            "...........KKaaaaaaaaaaaaaKK............",
            "..........KbbaaaaaaaaaaaaaaaK...........",
            ".........KbbbbbaaaaaaaaaaaaaaK..........",
            "........KbbbbbbbaaaaaaaaaaaaaaK.........",
            ".......KabbbbbbbaaaaaaaaaaaaaaaK........",
            "......KaabbbbbbbaaaaaaaaaaaaaaaaK.......",
            "......KaabbbbbbbaaaaaaaaaaaaaaaaK.......",
            ".....KaaabbbbbbbaaaaaaaaaaaaaaacaK......",
            ".....KaaaabbbbbbaaaaaaaaaaaaaaaacK......",
            "....KaaaaaaabbbaaaaaaaaaaaaaaaaaccK.....",
            "....KaaaaaaaaaaaaaaaaaaaaaaaaaaaacK.....",
            "....KaaaaaaaaaaaaaaaaaaaaaaaaaaaacK.....",
            "....KccccccccccccccccccccccccccccccK....",
            "....KccccccccccccccccccccccccccccccK....",
            "....KaaaaaaaaaaaaaaccaaaaaaaaaaaacK.....",
            "....KaaaaaaaaaaaaaaccaaaaaaaaaaaacK.....",
            "....KaaaaaaaaaaaaaaccaaaaaaaaaaaacK.....",
            ".....KaaaaaaaaaaaaaccaaaaaaaaaaacK......",
            ".....KaaaaaaaaaaaaaccaaaaaaaaaaacK......",
            "......KaaaaaaaaaaaaccaaaaaaaaaacK.......",
            "......KaaaaaaaaaacccccaaaaaaaaacK.......",
            ".......KaaaaaaaaacccccaaaaaaaacK........",
            "........KaaaaaaaacccccaaaaaaacK.........",
            ".........KaaaaaaacccccaaaaaacK..........",
            "..........KaaaaaaaaaaaaaaaccK...........",
            "...........KKaaaacccccccccKK............",
            ".............KKKaacccccKKK..............",
            "................KKKKKKK.................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xF2C230, "b": 0xFFF2A8, "c": 0xB5861A]
    )

    static let moon = PixelSprite(
        rows: [
            "........................................",
            "........................................",
            "........................................",
            "........................................",
            ".............KKKKKKK....................",
            "..........KKKaaaaaaaK...................",
            ".........KaaaaaaaaKK....................",
            "........KaaaaabbaK...............c......",
            ".......KaaaaaabbK...............cdc.....",
            "......KaaaaaaaaK.................c......",
            ".....KaaaaaaaaaK........................",
            "....KcaaaaaaaaK.........................",
            "...KacaaaaaaaaK.........................",
            "...KacaabbbaaK..........................",
            "...KacabbbbbaK..........................",
            "..KaacabbbbbaK..........................",
            "..KaacaabbbaaK..........................",
            "..KaacaaaaaaaK..........................",
            "..KaacaaaaaaaK..........................",
            "..KaacaaaaaaaK..........................",
            "..KaacaaaaaaaK..........................",
            "..KaacaaaaaaaaK.........................",
            "..KaacaaaaaaaaK.........................",
            "..KaacabbaaaaaaK........................",
            "..KaacbbbbaaaaaK........................",
            "...KacbbbbaaaaaaK.......................",
            "...KacabbaaaaaaaaK.................c....",
            "...KacaaaaaaaaaaaaKK..............cdc...",
            "....KaaaaaaaaaaaaaaaKK.............c....",
            ".....KaaaaaaabbaaaaaaaKKKKKKK...........",
            "......KaaaaabbbbaaaaaaaaaaaaaK..........",
            ".......KaaaabbbbaaaaaaaaaaaaK...........",
            "........KaaaabbaaaaaaaaaaaaK..c.........",
            ".........KaaaaaaaaaaaaaaaaK..cdc........",
            "..........KKKaaaaaaaaaaKKK....c.........",
            ".............KKKKKKKKKK.................",
            "........................................",
            "........................................",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xF7D454, "b": 0xE0B030, "c": 0xFFF2A8, "d": 0xF2C230]
    )

    static let octopus = PixelSprite(
        rows: [
            "........................................",
            "...............KKKKKKKKK................",
            ".............KKaaaaaaaaaKK..............",
            "...........KKaaaaaaaaaaaaaKK............",
            ".........KKaaaaaaaaaaaaaaaaaKK..........",
            "........KaabbbbaaaaaaaaaaaaaaaK.........",
            ".......KabbbbbbbaaaaaaaaaaaaaaaK........",
            "......KabbbbbbbbaaaaaaaaaaaaaaaaK.......",
            "......KabbbbbbbbaaaaaaaaaaaaaaaaK.......",
            ".....KaabbbbbbbbaaaaaaaaaaaaaaaaaK......",
            ".....KaabbbbbbbaaaaaaaaaaaaaaaacaK......",
            "....KaaaabbbbaaaaaaaaaaaaaaaaaaacaK.....",
            "....KaaaaaaadddaaaaaaaaadddaaaaaccK.....",
            "....KaaaaaadddddaaaaaaadddddaaaaccK.....",
            "....KaaaaadddddddaaaaadddddddaaaccK.....",
            "....KaaaaadddeeddaaaaadddeeddaaaccK.....",
            "....KaaaaaddeeeedaaaaaddeeeedaaaccK.....",
            "....KaaaaadddeeddaaaaadddeeddaaaccK.....",
            ".....KaaaaadddddaaaaaaadddddaaaacK......",
            ".....KaaaaaadddaaaaaaaaadddaaaaccK......",
            "......KaaaaaaaaaaacccaaaaaaaaaacK.......",
            "......KaaaaaaaaaaacccaaaaaaaaaccK.......",
            ".....KaaaaaaaaaaaacccaaaaaaacccccKK.....",
            "....KaaaaaaaaaaaaaaaaaaaaaacccccccKK....",
            "....KaaaaaaaaaaccaaaaaaacccccccccaKK....",
            "....KKaaaaaaaaaaccccccccccccccccaKaK....",
            "....KaKKaaaaaaaaaaccccccccccccaKKaaK....",
            "....KaabKKKKaaaaaaaacccccccKKKKabaaK....",
            "....KaaaaaKaKKKKKKKKKKKKKKKaaKaaaaaK....",
            "....KaaaaaKaaaaaKaaaaaaKaaaaaKaaaaaK....",
            "..KKaaaaaaKaaaaaKaaaaaaKaaaaaKaaaaaaKK..",
            ".KaaaaabaaKaabaaKaaabaaKaabaaKaabaaaaaK.",
            ".KaaaaaaaaKaaaaaKaaaaaaKaaaaaKaaaaaaaaK.",
            ".KaaaaaaaaKaaaaaKaaaaaaKaaaaaKaaaaaaaaK.",
            ".KaaaaaaaaKaaaaaKaaaaaaKaaaaaKaaaaaaaaK.",
            "..KKaaaaaaKaaaaaKKaaaaKKaaaaaKaaaaaaKK..",
            "....KKKaaK.KKaKK..KaaK..KKaKK.KKaKKK....",
            ".......KK....K.....KK.....K.....K.......",
            "........................................",
            "........................................",
        ],
        palette: ["K": 0x3A2A2A, "a": 0xE8674F, "b": 0xFFB39F, "c": 0xC94F3A, "d": 0xFFFFFF, "e": 0x2B2B33]
    )
}
